version: '3.8'

services:
  frontend:
    image: angulardoc
    container_name: angular
    ports:
      - "8085:80"
    environment:
      MYSQL_HOST: mysqlcontainer

  backend:
    image: imge
    container_name: backend
    ports:
      - "9001:8080"
    environment:
      MYSQL_HOST: mysqlcontainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: leasingdbCopie
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  mysql:
    image: mysql:5.7
    container_name: mysqlcontainer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leasingdbCopie
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    external:
      name: networkmysql
